name: Bench and Schema Validation

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  bench:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install optional deps
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml jsonschema

      - name: Run bench-run (sample)
        run: |
          python scripts/bench-run.py --task sample-task --cases all --recipe engineering/sample-recipe.md --provider openai --model gpt-5

      - name: Upload bench results
        uses: actions/upload-artifact@v4
        with:
          name: bench-results
          path: bench/**/results/*.json

      - name: Aggregate lockfile
        run: |
          python scripts/bench-aggregate.py

      - name: Upload lockfile
        uses: actions/upload-artifact@v4
        with:
          name: recipes-lock
          path: recipes.lock.json
