name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  # Markdown lint job removed. We focus on POML validation only.

  validate-poml-headers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Validate POML headers
        shell: bash
        run: |
          set -e
          files=$(git ls-files 'poml/**/*.poml' || true)
          if [ -n "$files" ]; then
            python scripts/check_poml_headers.py -- $files
          else
            echo "No POML files found"
          fi

  bench-smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Run bench smoke (engineering)
        run: |
          python scripts/bench-run.py --task sample-task --cases all --recipe poml/engineering/ai-engineer.poml --provider openai --model gpt-5
      - name: Run bench smoke (marketing)
        run: |
          python scripts/bench-run.py --task sample-task --cases all --recipe poml/marketing/content-creator.poml --provider openai --model gpt-5
